### ISSUE TITLE
Change dependency on rsbeams.rsphysics.rsconst to rsmath.const

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/rsfriction#1]

**Comment by gurhar1133** [comment]
can i get repo access here as well?
@robnagler

**Comment by robnagler** [comment]
done

**Comment by gurhar1133** [comment]
@robnagler was this closed cause it does not need to be changed? Or should rsbeams/rsphysics/rsconst usage be switched over to rsmath and scipy?

**Comment by robnagler** [comment]
I have no idea why I closed it. :)
